{
 "title": "Bjorn2Scan Nodes",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "staleness_window", "label": "Staleness window", "query": "6m,10m,16m,20m,30m,1h" },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": {
     "query": "label_values(bjorn2scan_deployment,deployment_name)"
    }
   },
   {
    "name": "deployment_uuid",
    "label": "Deployment UUID",
    "query": {
     "query": "label_values(bjorn2scan_deployment{deployment_name=~\"$deployment_name\"},deployment_uuid)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\"},node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_deployment{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) >0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Scanned",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Risk",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_node_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exploits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (last_over_time(bjorn2scan_node_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(deployment_name, bjorn2scan_version, deployment_type, deployment_console, grype_db_built, deployment_uuid) (last_over_time(bjorn2scan_deployment{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_node_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment_uuid) (last_over_time(bjorn2scan_node_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerabilities by OS",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Critical\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"High\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Medium\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Low\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Negligible\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Unknown\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (os_release)(last_over_time(bjorn2scan_node_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0) / sum by (os_release)(last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Vulnerability Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(node, os_release, architecture) (\n  last_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Critical\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"High\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Medium\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Low\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Negligible\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\", severity=\"Unknown\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability_risk{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (\n\tlast_over_time(bjorn2scan_node_vulnerability_exploited{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n) / sum by(node) (\n\tlast_over_time(bjorn2scan_node_scanned{deployment_uuid=~\"$deployment_uuid\", node=~\"$node\"}[$staleness_window]) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}